[package]
name = "ckb-notify"
version = "0.36.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
ckb-logger = { path = "../util/logger" }
ckb-app-config  = { path = "../util/app-config" }
ckb-types = { path = "../util/types" }
ckb-channel = { path = "../util/channel" }
ckb-stop-handler = { path = "../util/stop-handler" }

[dev-dependencies]
