[package]
name = "ckb-pow"
version = "0.36.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
byteorder = "1.3.1"
ckb-types = { path = "../util/types" }
ckb-hash = { path = "../util/hash"}
serde = { version = "1.0", features = ["derive"] }
eaglesong = "0.1"
log = "0.4"
