[package]
name = "ckb-occupied-capacity-macros"
version = "0.36.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
syn = "0.15"
ckb-occupied-capacity-core = { path = "../core" }
