[package]
name = "ckb-fixed-hash-macros"
version = "0.36.0-pre"
license = "MIT"
authors = ["Nervos <dev@nervos.org>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
ckb-fixed-hash-core = { path = "../core" }
quote = "0.6"
syn = "0.15"
proc-macro2 = "0.4"
