[package]
name = "ckb-db"
version = "0.36.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-app-config = { path = "../util/app-config" }
ckb-logger = { path = "../util/logger" }
ckb-error = { path = "../error" }
tempfile = "3.0"
libc = "0.2"
rocksdb = { package = "ckb-rocksdb", version = "=0.14.1", features = ["snappy"] }
