[package]
name = "ckb-chain"
version = "0.36.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-logger = { path = "../util/logger" }
ckb-metrics = { path = "../util/metrics" }
ckb-types = { path = "../util/types" }
ckb-shared = { path = "../shared" }
ckb-chain-spec = { path = "../spec" }
ckb-store = { path = "../store" }
ckb-verification = { path = "../verification" }
faketime = "0.2.0"
ckb-stop-handler = { path = "../util/stop-handler" }
ckb-dao = { path = "../util/dao" }
ckb-proposal-table = { path = "../util/proposal-table" }
ckb-error = { path = "../error" }
ckb-app-config = { path = "../util/app-config" }
bitflags = "1.0"
ckb-rust-unstable-port = { path = "../util/rust-unstable-port" }
ckb-channel = { path = "../util/channel" }

[dev-dependencies]
ckb-test-chain-utils = { path = "../util/test-chain-utils" }
ckb-dao-utils = { path = "../util/dao/utils" }
ckb-tx-pool = { path = "../tx-pool" }
ckb-jsonrpc-types = { path = "../util/jsonrpc-types" }
lazy_static = "1.4"
